name: Build and Helm Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          check-latest: true
      - name: Build CLI
        run: go build -o bin/ctx src/cli/main.go
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image (no push)
        run: docker build -t contexis-cmp/contexis:ci .
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Helm lint
        run: helm lint charts/contexis-app
      - name: Helm template
        run: helm template contexis charts/contexis-app --values charts/contexis-app/values.yaml


