name: Security - SBOM and Vulnerability Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sbom-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          check-latest: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build -t contexis-cmp/contexis:ci .
      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: contexis-cmp/contexis:ci
          output-file: sbom.spdx.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
      - name: Vulnerability Scan (Grype)
        uses: anchore/scan-action@v3
        with:
          image: contexis-cmp/contexis:ci
          fail-build: true
          output-format: sarif
          severity-cutoff: high
          only-fixed: true


